import type { WordBank } from "@writetogether/schema";

export type ModeTwoBank = WordBank & {
  category: "nouns" | "verbs" | "adjectives" | "adverbials" | "connectives" | "starters";
  topic: string;
};

export const modeTwoBanks: ModeTwoBank[] = [
  {
    id: "bank-nouns-antarctica",
    title: "Antarctica Nouns",
    description: "People, places and objects linked to Shackleton",
    level: "lks2",
    tags: ["topic:antarctica", "grammar:noun"],
    colourMap: undefined,
    category: "nouns",
    topic: "Antarctica",
    items: [
      { id: "n1", text: "iceberg", tags: ["tier:2"] },
      { id: "n2", text: "pack ice", tags: ["tier:2"] },
      { id: "n3", text: "crew", tags: ["tier:1"] },
      { id: "n4", text: "sled dogs", tags: ["tier:2"] },
      { id: "n5", text: "expedition", tags: ["tier:1"] },
      { id: "n6", text: "lifeboat", tags: ["tier:1"] },
      { id: "n7", text: "Endurance", tags: ["proper"] },
      { id: "n8", text: "Aurora Australis", tags: ["proper"] },
    ],
  },
  {
    id: "bank-verbs-antarctica",
    title: "Antarctica Verbs",
    description: "Action verbs for polar exploration narratives",
    level: "lks2",
    tags: ["topic:antarctica", "grammar:verb"],
    colourMap: undefined,
    category: "verbs",
    topic: "Antarctica",
    items: [
      { id: "v1", text: "navigated" },
      { id: "v2", text: "hauled" },
      { id: "v3", text: "chopped" },
      { id: "v4", text: "secured" },
      { id: "v5", text: "withstood" },
      { id: "v6", text: "signalled" },
      { id: "v7", text: "encouraged" },
    ],
  },
  {
    id: "bank-adjectives-antarctica",
    title: "Antarctica Adjectives",
    description: "Adjectives to add detail and texture",
    level: "lks2",
    tags: ["topic:antarctica", "grammar:adjective"],
    colourMap: undefined,
    category: "adjectives",
    topic: "Antarctica",
    items: [
      { id: "a1", text: "bitter" },
      { id: "a2", text: "glacial" },
      { id: "a3", text: "treacherous" },
      { id: "a4", text: "courageous" },
      { id: "a5", text: "unyielding" },
      { id: "a6", text: "snow-laden" },
    ],
  },
  {
    id: "bank-adverbials-time",
    title: "Time Adverbials",
    description: "Sentence starters for chronology",
    level: "lks2",
    tags: ["grammar:adverbial", "function:starter"],
    colourMap: undefined,
    category: "adverbials",
    topic: "General",
    items: [
      { id: "t1", text: "Before dawn," },
      { id: "t2", text: "Later that day," },
      { id: "t3", text: "After several hours," },
      { id: "t4", text: "Moments before impact," },
      { id: "t5", text: "At the same time," },
    ],
  },
  {
    id: "bank-connectives",
    title: "Connectives",
    description: "Join ideas and create cohesion",
    level: "lks2",
    tags: ["grammar:connective"],
    colourMap: undefined,
    category: "connectives",
    topic: "General",
    items: [
      { id: "c1", text: "because" },
      { id: "c2", text: "even though" },
      { id: "c3", text: "so that" },
      { id: "c4", text: "however" },
      { id: "c5", text: "as a result" },
    ],
  },
  {
    id: "bank-starters",
    title: "Sentence Starters",
    description: "Boost variety at paragraph level",
    level: "lks2",
    tags: ["grammar:starter"],
    colourMap: undefined,
    category: "starters",
    topic: "General",
    items: [
      { id: "s1", text: "Cautiously," },
      { id: "s2", text: "With determination," },
      { id: "s3", text: "Without warning," },
      { id: "s4", text: "In the distance," },
      { id: "s5", text: "Surprisingly," },
    ],
  },
];
